name: tomo-toolshed
channels:
  - conda-forge
dependencies:
  - python=3.10
  - click
  - pandas
  - lxml
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - mrcfile
  - connected-components-3d
  - pytest
  - pip
