name: segmentation-curator
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - click
  - mrcfile
  - connected-components-3d
  - pytest
  - pip
